services:
  - type: web
    name: evolvex-system
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn simple_app:app
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: SECRET_KEY
        generateValue: true
